# Generated by Django 4.2.4 on 2023-09-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_customfield_product_product_custom_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='custom_fields',
            field=models.ManyToManyField(related_name='products', to='userapp.customfield'),
        ),
    ]
