# Generated by Django 4.2.4 on 2023-09-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_product_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_fields',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
    ]
