# Generated by Django 4.2.4 on 2023-09-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_remove_product_custom_fields_delete_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_logged_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
