# Generated by Django 4.2.4 on 2023-09-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_remove_shippingaddress_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='name',
        ),
    ]
