# Generated by Django 4.2.4 on 2023-09-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_rename_full_name_shippingaddress_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
