# Generated by Django 4.2.4 on 2023-09-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_rename_phone_number_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
