# Generated by Django 4.2.4 on 2023-09-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
