# Generated by Django 4.2.4 on 2023-10-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
