# Generated by Django 4.2.4 on 2023-10-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0035_shippingaddress_address_line2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_line2',
        ),
    ]
