# Generated by Django 4.2.4 on 2024-02-01 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0040_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
