# Generated by Django 4.2.4 on 2024-02-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0043_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
    ]
