# Generated by Django 4.2.4 on 2024-02-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0045_appointment_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
