# Generated by Django 4.2.4 on 2024-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0048_remove_appointment_start_time_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
