# Generated by Django 4.2.4 on 2024-02-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0049_slots_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='time',
        ),
    ]
