# Generated by Django 4.2.4 on 2024-02-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0050_remove_slots_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='start_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
