# Generated by Django 4.2.4 on 2024-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0053_order_product_orderitem_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
