# Generated by Django 4.2.4 on 2024-03-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0062_orderitem_accepted_by_delivery_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='accepted_by_delivery_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
