# Generated by Django 4.2.4 on 2024-03-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0063_alter_orderitem_accepted_by_delivery_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='accepted_by_delivery_person',
            field=models.BooleanField(default=False),
        ),
    ]
