# Generated by Django 4.2.4 on 2024-03-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0064_alter_orderitem_accepted_by_delivery_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='driving_licenses/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
