# Generated by Django 4.2.4 on 2024-03-20 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0065_customuser_driving_license_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='accepted_by_delivery_person',
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
