# Generated by Django 4.2.4 on 2024-03-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0067_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], max_length=20),
        ),
    ]
