# Generated by Django 4.2.4 on 2024-03-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0068_remove_order_status_alter_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivered_at',
        ),
        migrations.AddField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
